mediaserver: fix compilation of libcameraservice
Fix the error:
error: frameworks/av/media/mediaserver/Android.bp:12:1: "mediaserver" depends on undefined module "libcameraservice"
Module "mediaserver" is defined in namespace "." which can read these 1 namespaces: ["."]
Module "libcameraservice" can be found in these namespaces: ["frameworks/av/services/camera/libcameraservice"]